import { performance } from "node:perf_hooks";import { AuditLogRepository, AuditService, AuthService, MemoryStore, OrganizationRepository, TreatmentRepository, UserRepository } from "./v2/modules.js";
const label="[合成测试数据]",note="本地沙盒压力测试，不代表生产环境性能。",results=[];
function run(name,count,fn){const start=performance.now();let status="通过",error="";try{fn()}catch(e){status="失败";error=e.message}results.push({name,count,label,status,elapsedMs:Math.round((performance.now()-start)*100)/100,error,note})}
const storage=new MemoryStore(),users=new UserRepository(storage),orgs=new OrganizationRepository(storage),treatments=new TreatmentRepository(storage),audits=new AuditLogRepository(storage),audit=new AuditService(audits),auth=new AuthService(users,audit,storage);
run("19 100个演示用户",100,()=>{const items=Array.from({length:100},(_,i)=>({id:`u${i}`,role:"viewer",organizationId:`o${i%10}`,displayName:`Demo ${i}`,status:"active",createdAt:"2026-01-01T00:00:00Z"}));users.save(items);if(users.list().length!==100)throw new Error("用户数不一致")});
run("20 10个演示机构",10,()=>{orgs.save(Array.from({length:10},(_,i)=>({id:`o${i}`,name:`Demo Clinic ${i}`,status:"active",createdAt:"2026-01-01T00:00:00Z"})));if(orgs.list().length!==10)throw new Error("机构数不一致")});
run("21 1,000条治疗记录",1000,()=>{treatments.save(Array.from({length:1000},(_,i)=>({id:`t${i}`,organizationId:`o${i%10}`,operatorId:`u${i%100}`,patientId:`p${i}`,planId:`plan${i}`,status:"sandbox",createdAt:"2026-01-01T00:00:00Z"})));if(treatments.list().length!==1000)throw new Error("治疗数不一致")});
run("22 10,000条操作事件",10000,()=>{const rows=Array.from({length:10000},(_,i)=>({id:`e${i}`,treatmentId:`t${i%1000}`,eventType:"region_completed",regionId:`r${i%5}`,timestamp:"2026-01-01T00:00:00Z",source:"synthetic"}));storage.setItem("v2_device_events",JSON.stringify(rows));if(JSON.parse(storage.getItem("v2_device_events")).length!==10000)throw new Error("事件数不一致")});
run("23 1,000条审计日志",1000,()=>{audits.save(Array.from({length:1000},(_,i)=>({id:`a${i}`,actorId:`u${i%100}`,organizationId:`o${i%10}`,action:"view_log",resourceType:"treatment",resourceId:`t${i%1000}`,timestamp:"2026-01-01T00:00:00Z",result:"success",source:"stress"})));if(audits.list().length!==1000)throw new Error("审计数不一致")});
console.table(results);const failed=results.filter(x=>x.status==="失败");console.log(JSON.stringify({label,note,total:results.length,passed:results.length-failed.length,failed:failed.length,results},null,2));if(failed.length)process.exitCode=1;
