import { AIResultRepository, AuditLogRepository, AuditService, AuthService, CSVDeviceAdapter, DeviceEventRepository, FutureVisionProvider, MockAIProvider, NPSRepository, OrganizationRepository, OrganizationService, PatientRepository, PatientService, ROIRepository, RuleBasedProvider, TreatmentRepository, UserRepository, V2_KEYS, VideoJobRepository, VideoJobService, calculateNPS, calculateROI, deleteOrganizationData, exportSandbox } from "./modules.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const repos={users:new UserRepository(),orgs:new OrganizationRepository(),patients:new PatientRepository(),treatments:new TreatmentRepository(),deviceEvents:new DeviceEventRepository(),videoJobs:new VideoJobRepository(),aiResults:new AIResultRepository(),roi:new ROIRepository(),nps:new NPSRepository(),auditLogs:new AuditLogRepository()};
const audit=new AuditService(repos.auditLogs),auth=new AuthService(repos.users,audit),orgService=new OrganizationService(repos.orgs,auth,audit),patientService=new PatientService(repos.patients,auth,audit),videoService=new VideoJobService(repos.videoJobs,audit);
const toast=message=>{$("#toast").textContent=message;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1800)};
const output=(id,value)=>{const target=$(id);if(!target)return;target.textContent=typeof value==="string"?value:formatResult(value)};
const formatResult=value=>{if(value?.events)return value.errors?.length?`导入失败：${value.errors.join("；")}`:`导入完成：共 ${value.events.length} 条演示记录，等待人工确认。`;if(value?.role)return`登录成功：当前角色为 ${roleName(value.role)}。`;if(value?.status==="queued")return`任务已创建：${value.fileName}，当前状态为等待处理。`;if(value?.status==="not_implemented")return"该能力尚未接入，不会产生分析结果。";if(value?.explanation)return`${value.explanation} 所有结果需人工确认。`;if(value?.value!==undefined)return value.value===null?"暂无数据":`当前结果：${value.value}（${value.count}条评价）`;if(value&&typeof value==="object"&&Object.keys(value).every(k=>["保守","中性","乐观"].includes(k)))return Object.entries(value).map(([k,v])=>`${k}情景：${v.netScenarioValue}`).join(" ｜ ");return"操作已完成。"};
const roleName=role=>({platform_admin:"系统管理员",org_admin:"机构负责人",medical_operator:"操作医生",front_desk:"前台人员",patient:"患者",viewer:"只读查看"}[role]||role);
function seed(){if(!repos.orgs.list().length){repos.orgs.save([{id:"demo-org-a",name:"Demo Clinic A",status:"active",createdAt:new Date().toISOString()},{id:"demo-org-b",name:"Demo Clinic B",status:"active",createdAt:new Date().toISOString()}])}if(!repos.users.list().length)auth.register({role:"platform_admin",displayName:"Demo Admin",password:"demo123"})}
function session(){return auth.session()}
function render(){const s=session();$("#session-status").textContent=s?`${roleName(s.role)} · ${s.organizationId||"全部机构"}`:"未登录";const options=repos.orgs.list().map(x=>`<option value="${x.id}" ${s?.organizationId===x.id?"selected":""}>${x.name}</option>`).join("");$("#reg-org").innerHTML=`<option value="">无机构</option>${options}`;$("#org-switch").innerHTML=options;const patients=patientService.list(s);$("#patient-list").innerHTML=patients.length?patients.map(x=>`<article><span>${x.demoName}</span><small>${x.organizationId} · 演示数据</small></article>`).join(""):"当前权限范围内暂无演示患者";const patientTreatments=s?.role==="patient"?auth.scope(repos.treatments.list(),s):[];$("#patient-treatment-list").innerHTML=patientTreatments.length?patientTreatments.map(x=>`<article><span>${x.createdAt.slice(0,10)} · ${(x.authorizedRegions||[]).join("、")||"无授权区域"}</span><small>${x.qualitySummary||"暂无质量摘要"} · 术后说明占位</small></article>`).join(""):"当前没有可见的本人演示治疗记录";$("#org-stats").innerHTML=`<span>机构 ${repos.orgs.list().length}</span><span>患者 ${patients.length}</span><span>治疗 ${auth.scope(repos.treatments.list(),s).length}</span>`;renderAudit()}
function renderAudit(){const labels={register:"添加演示人员",login:"登录",logout:"退出登录",permission_denied:"权限不足",create_org:"新建机构",switch_org:"切换机构",create_demo_patient:"新建匿名档案",import_device_data:"导入演示数据",upload_video:"创建视频任务",generate_ai_result:"生成辅助结果",view_logs:"查看操作记录",export_data:"导出数据",delete_data:"删除数据"};const rows=auth.scope(repos.auditLogs.list(),session()).slice(-30).reverse();$("#audit-list").innerHTML=rows.length?rows.map(x=>`<article><span>${labels[x.action]||"系统操作"} · ${x.result==="success"?"成功":"未完成"}</span><small>${x.actorId?"演示人员":"未登录用户"} · ${new Date(x.timestamp).toLocaleString("zh-CN")}</small></article>`).join(""):"暂无操作记录。登录后进行一次页面操作即可查看。"}
$$('[data-panel]').forEach(b=>b.onclick=()=>{$$('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.panel));$$('.panel').forEach(x=>x.classList.toggle('active',x.id===b.dataset.panel));history.replaceState(null,'',`${location.pathname}${location.search}#${b.dataset.panel}`);if(b.dataset.panel==='audit'&&session())audit.record({actorId:session().userId,organizationId:session().organizationId,action:'view_logs',resourceType:'audit_log'})});
$("#register-form").onsubmit=e=>{e.preventDefault();try{const user=auth.register({role:$("#reg-role").value,organizationId:$("#reg-org").value||null,displayName:$("#reg-name").value,password:$("#reg-password").value});output("#access-output",user);render()}catch(err){toast(err.message)}};
$("#login-form").onsubmit=e=>{e.preventDefault();try{output("#access-output",auth.login({displayName:$("#login-name").value,password:$("#login-password").value}));render()}catch(err){output("#access-output",err.message)}};
$("#logout").onclick=()=>{auth.logout();render()};
$("#org-switch").onchange=()=>{try{orgService.switch($("#org-switch").value,session());render()}catch(err){toast(err.message);render()}};
$("#patient-form").onsubmit=e=>{e.preventDefault();try{patientService.create({organizationId:session()?.organizationId,demoName:$("#patient-name").value},session());render();toast("已创建匿名演示档案")}catch(err){toast(err.message)}};
$("#import-device").onclick=()=>{try{auth.require("device.import");const result=new CSVDeviceAdapter().parse($("#device-csv").value);result.events.forEach(x=>repos.deviceEvents.add(x));audit.record({actorId:session()?.userId,organizationId:session()?.organizationId,action:"import_device_data",resourceType:"device_event",result:result.errors.length?"rejected":"success",source:"sandbox_csv"});output("#adapter-output",result)}catch(err){output("#adapter-output",err.message)}};
$("#create-video").onclick=()=>{try{auth.require("video.create");output("#assist-output",videoService.create({treatmentId:"t-demo",fileName:$("#video-name").value,size:1024,type:"video/mp4"},session()))}catch(err){output("#adapter-output",err.message)}};
function ai(provider){try{auth.require("ai.generate");const result=provider.generate({id:"synthetic-event",eventType:"region_completed"});repos.aiResults.add(result);audit.record({actorId:session()?.userId,organizationId:session()?.organizationId,action:"generate_ai_result",resourceType:"ai_result",resourceId:result.id});output("#assist-output",result)}catch(err){output("#assist-output",err.message)}}
$("#rule-ai").onclick=()=>ai(new RuleBasedProvider());$("#mock-ai").onclick=()=>ai(new MockAIProvider());$("#future-ai").onclick=()=>ai(new FutureVisionProvider());
const roiFields=[['orgCount','试点机构数'],['annualTreatments','每机构年治疗量'],['complaintRate','当前客诉率'],['avoidableRate','预估可避免比例'],['complaintCost','单次客诉成本'],['repurchaseLift','潜在复购提升比例'],['repurchaseContribution','单次复购贡献'],['deploymentCost','系统部署成本'],['annualOperatingCost','年度运营成本']];$("#roi-fields").innerHTML=roiFields.map(([id,label])=>`<label>${label}<input type="number" min="0" step="any" id="roi-${id}" placeholder="手动输入"></label>`).join("");
$("#roi-form").onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(roiFields.map(([id])=>[id,$(`#roi-${id}`).value]));const factors={保守:.7,中性:1,乐观:1.3};const result=Object.fromEntries(Object.entries(factors).map(([name,f])=>[name,calculateROI({...values,avoidableRate:Number(values.avoidableRate||0)*f,repurchaseLift:Number(values.repurchaseLift||0)*f})]));repos.roi.add({id:`roi-${Date.now()}`,values,result,source:"user_input_scenario",createdAt:new Date().toISOString()});output("#roi-output",result)};
$("#nps-form").onsubmit=e=>{e.preventDefault();const record={id:`nps-${Date.now()}`,group:$("#nps-group").value,score:Number($("#nps-score").value),isDemo:$("#nps-demo").checked,source:$("#nps-demo").checked?"sandbox_demo":"user_input",createdAt:new Date().toISOString()};repos.nps.add(record);output("#nps-output",calculateNPS(repos.nps.list(),record.group))};
$("#refresh-audit").onclick=renderAudit;$("#export-data").onclick=()=>{try{auth.require("sandbox.export");audit.record({actorId:session().userId,organizationId:session().organizationId,action:"export_data",resourceType:"sandbox"});exportSandbox(repos);toast("演示数据已准备导出") }catch(err){toast(err.message)}};$("#delete-data").onclick=()=>{try{auth.require("sandbox.delete");const id=session()?.organizationId;if(!id)throw new Error("请先选择演示机构");const deleted=deleteOrganizationData(id,repos);audit.record({actorId:session().userId,organizationId:id,action:"delete_data",resourceType:"organization",resourceId:id});toast(`已删除 ${deleted} 条当前机构沙盒数据`);render()}catch(err){toast(err.message)}};
seed();render();
const hashPanel={patients:"orgs",data:"data",assist:"assist"}[location.hash.slice(1)];
if(hashPanel)document.querySelector(`#tabs [data-panel="${hashPanel}"]`)?.click();
const drawer=$("#nav-drawer"),backdrop=$("#drawer-backdrop"),menu=$("#mobile-menu");let drawerTrigger=null;const closeDrawer=()=>{drawer.setAttribute("aria-hidden","true");backdrop.hidden=true;menu.setAttribute("aria-expanded","false");drawerTrigger?.focus()};menu.onclick=e=>{drawerTrigger=e.currentTarget;drawer.setAttribute("aria-hidden","false");backdrop.hidden=false;menu.setAttribute("aria-expanded","true");$("#drawer-close").focus()};$("#drawer-close").onclick=closeDrawer;backdrop.onclick=closeDrawer;drawer.querySelectorAll("[data-panel]").forEach(x=>x.addEventListener("click",closeDrawer));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDrawer()});
