const $=selector=>document.querySelector(selector);const usesDevelopmentProxy=["127.0.0.1","localhost"].includes(location.hostname)&&location.port==="4173";const API=usesDevelopmentProxy?"http://127.0.0.1:4174/api/ai":"/api/ai";let planDraft=null;
const labels={idle:"智能功能未配置",ready:"服务已配置",loading:"调用中",success:"智能生成 / 待人工确认",error:"调用失败",timeout:"调用超时",invalid:"输出格式错误",confirmed:"已人工确认"};
function setState(prefix,state){const status=$(`#${prefix}-ai-status`);if(!status)return;status.textContent=labels[state];status.className=`status-badge ${state==="success"||state==="confirmed"?"success":state==="loading"?"info":state==="idle"?"muted":"warning"}`;const button=$(`#smart-${prefix}-button`);if(button){button.disabled=state==="loading";button.setAttribute("aria-busy",String(state==="loading"));button.textContent=state==="loading"?"处理中…":prefix==="plan"?"智能创建":prefix==="summary"?"智能摘要":"智能查询"}}
async function request(path,body){const response=await fetch(`${API}/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return response.json()}
function errorState(prefix,result){const state=result.error?.code==="TIMEOUT"?"timeout":result.error?.code==="INVALID_JSON"||result.error?.code==="SCHEMA_INVALID"?"invalid":"error";setState(prefix,state);$(`#smart-${prefix}-result`).textContent=result.error?.message||"智能功能暂时不可用，请使用手动方式继续。"}
async function loadStatus(){try{const response=await fetch(`${API}/status`),status=await response.json();document.querySelectorAll(".ai-assistant .source-tag").forEach(tag=>tag.textContent=status.configured?`真实模型 · ${status.model}`:"智能功能未配置");for(const prefix of ["plan","summary","query"]){setState(prefix,status.configured?"ready":"idle")}document.querySelectorAll(".ai-result").forEach(el=>{if(status.configured)el.textContent="已连接智能服务，所有结果仍需人工确认。"})}catch{for(const prefix of ["plan","summary","query"])setState(prefix,"idle")}}
$("#smart-plan-button").addEventListener("click",async()=>{const input=$("#smart-plan-input").value.trim();if(!input){$("#smart-plan-result").textContent="请先输入治疗计划描述。";return}setState("plan","loading");try{const result=await request("plan",{input});if(!result.success)return errorState("plan",result);planDraft=result.result;setState("plan","success");$("#smart-plan-result").innerHTML=`<strong>计划草稿</strong><p>本次区域：${planDraft.allowedRegions.join("、")||"未识别"}</p><p>重点关注：${planDraft.attentionRegions.join("、")||"无"}</p><p>待澄清：${[...planDraft.clarifyingQuestions,...planDraft.uncertainItems].join("；")||"无"}</p>`;$("#confirm-plan-draft").hidden=false}catch{errorState("plan",{error:{message:"智能服务暂时不可用，请使用手动方式继续。"}})}});
$("#confirm-plan-draft").addEventListener("click",()=>{if(!planDraft)return;const treatment=$("#treatment-type");if([...treatment.options].some(x=>x.value===planDraft.treatmentType)){treatment.value=planDraft.treatmentType;treatment.dispatchEvent(new Event("change"))}setTimeout(()=>{document.querySelectorAll('#allowed-options input[type="checkbox"]').forEach(input=>{input.checked=planDraft.allowedRegions.includes(input.value)});if(planDraft.operatorNotes)$("#notes").value=planDraft.operatorNotes;setState("plan","confirmed");$("#smart-plan-result").insertAdjacentHTML("beforeend","<p><strong>草稿已填入表单，请逐项复核后继续。</strong></p>");$("#confirm-plan-draft").hidden=true},0)});
$("#smart-summary-button").addEventListener("click",async()=>{if(!$("#log").classList.contains("active")){setState("summary","error");$("#smart-summary-result").textContent="请先完成记录并生成质量报告。";return}const qualityLog={treatment:$("#log-plan").textContent,metrics:$("#log-metrics").textContent,reviewItems:$("#unresolved-list").textContent,timeline:$("#log-deviations").textContent,status:"pending_review"};setState("summary","loading");try{const result=await request("summary",{qualityLog,audience:"operator"});if(!result.success)return errorState("summary",result);setState("summary","success");$("#smart-summary-result").innerHTML=`<strong>智能摘要</strong><p>${result.result.summary}</p><p><strong>待复核：</strong>${result.result.itemsToReview.join("；")||"无"}</p>`;$("#confirm-summary").hidden=false}catch{errorState("summary",{error:{message:"智能服务暂时不可用，原质量报告仍可正常使用。"}})}});
$("#confirm-summary").addEventListener("click",()=>{setState("summary","confirmed");$("#confirm-summary").hidden=true;$("#smart-summary-result").insertAdjacentHTML("beforeend","<p><strong>摘要已人工确认，原始质量报告未被修改。</strong></p>")});
$("#smart-query-button").addEventListener("click",async()=>{const input=$("#smart-query-input").value.trim();if(!input){$("#smart-query-result").textContent="请输入查询问题。";return}setState("query","loading");try{const result=await request("query",{input});if(!result.success)return errorState("query",result);setState("query","success");const count=result.result.intent==="count_records"?0:null;$("#smart-query-result").innerHTML=result.result.intent==="unknown"?`<strong>需要补充信息</strong><p>${result.result.clarifyingQuestions.join("；")||"暂时无法准确理解，请使用筛选条件查询。"}</p>`:`<strong>已转换为只读查询</strong><p>${count===0?"当前本地没有符合条件的记录。":"请在最近治疗记录中查看筛选结果。"}</p><small>查询结果来自本地记录，模型未直接读取数据。</small>`}catch{errorState("query",{error:{message:"智能功能暂时不可用，请使用手动方式继续。"}})}});
const jumpToAI=$("#jump-to-ai");if(jumpToAI)jumpToAI.addEventListener("click",()=>{$("#smart-query-title")?.scrollIntoView({behavior:"smooth",block:"start"});setTimeout(()=>$("#smart-query-input")?.focus(),300)});
loadStatus();
