import { prompts } from "./prompts.js";
import { RESPONSE_SCHEMAS, SCHEMAS } from "./schemas.js";
import { containsTreatmentParameters, detectSensitiveText, sanitizeInputFields, validateBusinessRules } from "./guardrails.js";
const id=()=>`llm-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const now=()=>new Date().toISOString();
const safeError=(operation,requestId,code,message,meta={})=>({success:false,requestId,provider:meta.provider||"configured-provider",model:meta.model||"configured-model",operation,result:null,requiresHumanConfirmation:true,isSynthetic:false,source:"real_llm",createdAt:now(),error:{code,message}});
export class LLMService{
 constructor({baseUrl,apiKey,model,timeoutMs=30000,fetchImpl=globalThis.fetch,audit=()=>{}}={}){Object.assign(this,{baseUrl,apiKey,model,timeoutMs:Number(timeoutMs),fetchImpl,audit})}
 configured(){return Boolean(this.baseUrl&&this.apiKey&&this.model)}
 async generateStructuredPlan(input,context={}){return this.call("generateStructuredPlan",input,context)}
 async summarizeQualityLog(qualityLog,audience="operator"){return this.call("summarizeQualityLog",qualityLog,{audience})}
 async parseNaturalLanguageQuery(input,context={}){return this.call("parseNaturalLanguageQuery",input,context)}
 async call(operation,input,context={}){const requestId=id(),started=Date.now(),meta={provider:"openai-compatible",model:this.model||"unconfigured"};const finish=(response,valid=false)=>{this.audit({requestId,operation,provider:meta.provider,model:meta.model,status:response.success?"success":response.error?.code||"failed",duration:Date.now()-started,inputFieldNames:sanitizeInputFields(typeof input==="object"?input:{input}),outputSchemaValid:valid,requiresHumanConfirmation:true,isSynthetic:false,createdAt:now(),errorCode:response.error?.code||null});return response};
  if(!this.configured())return finish(safeError(operation,requestId,"NOT_CONFIGURED","智能功能未配置，当前请使用手动方式。",meta));
  const text=typeof input==="string"?input:JSON.stringify(input);const sensitive=detectSensitiveText(text);if(sensitive.length)return finish(safeError(operation,requestId,"SENSITIVE_DATA_DETECTED","检测到可能的敏感信息，请删除后再使用智能功能。",meta));
  if(operation==="generateStructuredPlan"&&containsTreatmentParameters(text))return finish(safeError(operation,requestId,"TREATMENT_PARAMETER_BLOCKED","智能助手不能处理治疗参数，请使用手动方式继续。",meta));
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{const prompt=prompts[operation];const response=await this.fetchImpl(`${this.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${this.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:this.model,temperature:0,response_format:{type:"json_schema",json_schema:{name:operation,strict:true,schema:RESPONSE_SCHEMAS[operation]}},messages:[{role:"system",content:prompt.system},{role:"user",content:prompt.buildUser(input,context)}]}),signal:controller.signal});const body=await response.json().catch(()=>null);if(!response.ok)throw Object.assign(new Error(body?.error?.message||"provider error"),{code:"PROVIDER_ERROR"});let result;try{result=JSON.parse(body?.choices?.[0]?.message?.content||"")}catch{return finish(safeError(operation,requestId,"INVALID_JSON","智能结果格式错误，请使用手动方式继续。",meta))}const schema=SCHEMAS[operation](result);if(!schema.valid){this.audit({requestId,operation,status:"schema_invalid_detail",validationErrors:schema.errors,inputFieldNames:sanitizeInputFields(typeof input==="object"?input:{input}),createdAt:now()});return finish(safeError(operation,requestId,"SCHEMA_INVALID","智能结果无法直接使用，请人工确认或改用手动输入。",meta));}const rules=validateBusinessRules(operation,result,context);if(!rules.valid)return finish(safeError(operation,requestId,rules.errors[0].split(":")[0],"智能结果无法直接使用，请人工确认或改用手动输入。",meta),true);return finish({success:true,requestId,...meta,operation,result,requiresHumanConfirmation:true,isSynthetic:false,source:"real_llm",createdAt:now(),error:null},true)}catch(error){const timeout=error.name==="AbortError";return finish(safeError(operation,requestId,timeout?"TIMEOUT":"TIMEOUT_OR_PROVIDER_ERROR",timeout?"智能处理超时，请使用手动方式继续。":"智能服务暂时不可用，请使用手动方式继续。",meta))}finally{clearTimeout(timer)}}
}
