const PLAN_KEYS = ["allowedRegions","attentionRegions","excludedRegions","treatmentType","operatorNotes","clarifyingQuestions","uncertainItems","requiresHumanConfirmation"];
const SUMMARY_KEYS = ["summary","completedItems","itemsToReview","timelineSummary","operatorVersion","patientFriendlyVersion","requiresHumanConfirmation"];
const QUERY_KEYS = ["intent","status","dateRange","filters","recordId","answerMode","clarifyingQuestions","requiresHumanConfirmation"];
const arrays = (value, keys) => keys.every((key) => Array.isArray(value[key]) && value[key].every((item) => typeof item === "string"));
const exactKeys = (value, keys) => value && typeof value === "object" && !Array.isArray(value) && Object.keys(value).every((key) => keys.includes(key)) && keys.every((key) => key in value);
export function validatePlanSchema(value) { const errors=[]; if(!exactKeys(value,PLAN_KEYS))errors.push("字段不完整或包含额外字段"); if(!arrays(value,["allowedRegions","attentionRegions","excludedRegions","clarifyingQuestions","uncertainItems"]))errors.push("区域和问题字段必须为文字数组"); if(typeof value?.treatmentType!=="string"||typeof value?.operatorNotes!=="string")errors.push("治疗项目和备注必须为文字"); if(value?.requiresHumanConfirmation!==true)errors.push("必须保留人工确认"); return{valid:errors.length===0,errors}; }
export function validateSummarySchema(value) { const errors=[]; if(!exactKeys(value,SUMMARY_KEYS))errors.push("字段不完整或包含额外字段"); if(!arrays(value,["completedItems","itemsToReview"]))errors.push("完成项和复核项必须为文字数组"); for(const key of ["summary","timelineSummary","operatorVersion","patientFriendlyVersion"])if(typeof value?.[key]!=="string")errors.push(`${key}必须为文字`); if(value?.requiresHumanConfirmation!==true)errors.push("必须保留人工确认"); return{valid:errors.length===0,errors}; }
export function validateQuerySchema(value) { const errors=[]; if(!exactKeys(value,QUERY_KEYS))errors.push("字段不完整或包含额外字段"); if(!["list_records","count_records","summarize_record","unknown"].includes(value?.intent))errors.push("查询意图不在白名单"); if(!["table","summary","clarification"].includes(value?.answerMode))errors.push("展示方式不在白名单"); if(!value?.dateRange||typeof value.dateRange.start!=="string"||typeof value.dateRange.end!=="string")errors.push("日期范围无效"); if(!value?.filters||![true,false,null].includes(value.filters.hasReviewItems)||![true,false,null].includes(value.filters.hasRestrictedAlerts))errors.push("筛选条件无效"); if(!Array.isArray(value?.clarifyingQuestions))errors.push("澄清问题必须为数组"); if(value?.requiresHumanConfirmation!==true)errors.push("必须保留人工确认"); return{valid:errors.length===0,errors}; }
export const SCHEMAS={generateStructuredPlan:validatePlanSchema,summarizeQualityLog:validateSummarySchema,parseNaturalLanguageQuery:validateQuerySchema};
const strings={type:"array",items:{type:"string"}};const base=(properties,required)=>({type:"object",additionalProperties:false,properties,required});
export const RESPONSE_SCHEMAS={
 generateStructuredPlan:base({allowedRegions:strings,attentionRegions:strings,excludedRegions:strings,treatmentType:{type:"string"},operatorNotes:{type:"string"},clarifyingQuestions:strings,uncertainItems:strings,requiresHumanConfirmation:{type:"boolean",const:true}},PLAN_KEYS),
 summarizeQualityLog:base({summary:{type:"string"},completedItems:strings,itemsToReview:strings,timelineSummary:{type:"string"},operatorVersion:{type:"string"},patientFriendlyVersion:{type:"string"},requiresHumanConfirmation:{type:"boolean",const:true}},SUMMARY_KEYS),
 parseNaturalLanguageQuery:base({intent:{type:"string",enum:["list_records","count_records","summarize_record","unknown"]},status:{type:"string"},dateRange:base({start:{type:"string"},end:{type:"string"}},["start","end"]),filters:base({hasReviewItems:{type:["boolean","null"]},hasRestrictedAlerts:{type:["boolean","null"]}},["hasReviewItems","hasRestrictedAlerts"]),recordId:{type:"string"},answerMode:{type:"string",enum:["table","summary","clarification"]},clarifyingQuestions:strings,requiresHumanConfirmation:{type:"boolean",const:true}},QUERY_KEYS)
};
